import Head from "next/head";
import axios from "axios";
import Card from "../components/Card/Card";
import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { getCharactersData } from "../state/actions/charactersActions";
import styles from "@/styles/Home.module.css";

export default function Home() {

  const charactersData = useSelector(
    (state: any) => state?.characters?.charactersData
  );
  
  const dispatch = useDispatch();
  const [url, setUrl] = useState("https://rickandmortyapi.com/api/character")

  const fetchCharacters = async () => {
    await axios.get(url).then((res) => {
      dispatch(getCharactersData(res.data.results));
      console.log(res.data.results);
    });
  };

  useEffect(() => {
    fetchCharacters();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!charactersData && charactersData == undefined ? (
          <>
            <span>Loading</span>
          </>
        ) : (
          charactersData.map((c: { image: string; name: string }) => (
            <Card img={c.image} name={c.name} />
          ))
        )}
      </main>
    </>
  );
}
